print("Welcome To Tip Calculator")
bill=float(input("What is the total bill? $"))
tip=int(input("How much tip would you like to give? 10, 12 or 15?"))
people=int(input("How many people to split bill with?"))
final_amount=round((bill+bill*tip/100)/people,2)
print(f"Each person should pay: ${final_amount}")
