data = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 651, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 504, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 430, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'follower_count': 394, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower_count': 400, 'description': 'Entrepreneur', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'follower_count': 370, 'description': 'Media Personality', 'country': 'USA'},
    {'name': 'Beyoncé', 'follower_count': 320, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Taylor Swift', 'follower_count': 310, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Virat Kohli', 'follower_count': 260, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Narendra Modi', 'follower_count': 200, 'description': 'Prime Minister', 'country': 'India'},
    {'name': 'Shah Rukh Khan', 'follower_count': 140, 'description': 'Actor', 'country': 'India'},
    {'name': 'Emma Watson', 'follower_count': 90, 'description': 'Actress', 'country': 'UK'},
    {'name': 'Robert Downey Jr.', 'follower_count': 100, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Leonardo DiCaprio', 'follower_count': 100, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Zendaya', 'follower_count': 180, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Tom Holland', 'follower_count': 140, 'description': 'Actor', 'country': 'UK'},
    {'name': 'Ryan Reynolds', 'follower_count': 90, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Drake', 'follower_count': 120, 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'Justin Bieber', 'follower_count': 270, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Billie Eilish', 'follower_count': 120, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Ed Sheeran', 'follower_count': 130, 'description': 'Singer', 'country': 'UK'},
    {'name': 'The Weeknd', 'follower_count': 100, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Rihanna', 'follower_count': 150, 'description': 'Singer', 'country': 'Barbados'},
    {'name': 'Post Malone', 'follower_count': 110, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Chris Hemsworth', 'follower_count': 80, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Katy Perry', 'follower_count': 110, 'description': 'Singer', 'country': 'USA'},
    {'name': 'David Beckham', 'follower_count': 110, 'description': 'Footballer', 'country': 'UK'},
    {'name': 'Kevin Hart', 'follower_count': 140, 'description': 'Comedian', 'country': 'USA'},
    {'name': 'Bruno Mars', 'follower_count': 100, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Johnny Depp', 'follower_count': 90, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Lady Gaga', 'follower_count': 130, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Megan Fox', 'follower_count': 50, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Jennifer Lopez', 'follower_count': 180, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Zayn Malik', 'follower_count': 50, 'description': 'Singer', 'country': 'UK'},
    {'name': 'Nicki Minaj', 'follower_count': 140, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower_count': 250, 'description': 'Model', 'country': 'USA'},
    {'name': 'Gigi Hadid', 'follower_count': 90, 'description': 'Model', 'country': 'USA'},
    {'name': 'Dua Lipa', 'follower_count': 100, 'description': 'Singer', 'country': 'UK'},
    {'name': 'Will Smith', 'follower_count': 90, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Chris Evans', 'follower_count': 110, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Gal Gadot', 'follower_count': 110, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'BTS', 'follower_count': 74, 'description': 'Music Group', 'country': 'South Korea'},
    {'name': 'BLACKPINK', 'follower_count': 57, 'description': 'Music Group', 'country': 'South Korea'},
    {'name': 'PSY', 'follower_count': 50, 'description': 'Singer', 'country': 'South Korea'},
    {'name': 'Shakira', 'follower_count': 100, 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Camila Cabello', 'follower_count': 60, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Maluma', 'follower_count': 90, 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Vin Diesel', 'follower_count': 80, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Jennifer Aniston', 'follower_count': 100, 'description': 'Actress', 'country': 'USA'},
]