menu={
    'espresso':{
        'ingredients':{
            'water':50,
            'coffee':18,
        },
        'cost':1.50
    },
    'latte':{
        'ingredients':{
            'water':200,
            'coffee':24,
            'milk':150
        },
        'cost':2.50
    },
    'cappuccino':{
        'ingredients':{
            'water':250,
            'coffee':24,
            'milk':100
        },
        'cost':3.00
    }
}
resources={
    'water':300,
    'coffee':150,
    'milk':200,
    'money':0
}